# Trading Bot Configuration


# Trading Parameters
trading:
  max_position_size: 100  # Maximum position size in USD
  risk_per_trade: 0.02   # 2% risk per trade
  initial_capital: 500   # Starting capital in USD

# Technical Analysis Parameters
technical:
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  ema:
    short_period: 9
    long_period: 21

# Sentiment Analysis
sentiment:
  news_lookback_hours: 24
  min_confidence: 0.7

# Risk Management
risk:
  max_drawdown: 0.15    # 15% maximum drawdown
  stop_loss: 0.02       # 2% stop loss
  take_profit: 0.04     # 4% take profit

  # Portfolio Configuration
  portfolio:
    rebalance_frequency: 7    # Days between portfolio rebalancing
    min_position_weight: 0.05  # Minimum allocation per asset (5%)
    max_position_weight: 0.30  # Maximum allocation per asset (30%)
    target_assets:
      - BTC/USD
      - ETH/USD
      - SOL/USD
      - ADA/USD
    risk_tolerance: moderate   # Can be: conservative, moderate, aggressive
    
    # Watchlist - stocks to monitor for potential investment
    watchlist:
      - NVDA    # NVIDIA - AI/semiconductor leader
      - GOOGL   # Google - Tech giant
      - AMD     # AMD - Semiconductor competitor
      - TSLA    # Tesla - EV leader
      - META    # Meta - Social media/VR