name: Portfolio Snapshot

on:
  schedule:
    # 9:30 AM ET (2:30 PM UTC) and 4:00 PM ET (9:00 PM UTC)
    - cron: '30 14 * * 1-5'  # 9:30 AM ET - Market open
    - cron: '0 21 * * 1-5'   # 4:00 PM ET - Market close
  workflow_dispatch:  # Allow manual trigger

jobs:
  snapshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        run: |
          poetry install --only=main --no-root
          
      - name: Run portfolio snapshot
        env:
          # These get the values from GitHub Secrets
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          poetry run python scripts/daily_snapshot.py
          
      - name: Commit and push data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update portfolio data $(date)" || exit 0
          git push
